### ISSUE TITLE
Search input field on home page

### ISSUE THREAD

**Issue by konqa** [MWS-3/care-central-web#15]
**Is your feature request related to a problem? Please describe.**
There is a need to test data flow from front end to back end.

**Describe the solution you'd like**
A basic search input form on home page. This will in future be styled as per supplied design.

**Describe alternatives you've considered**

**Additional context**
https://xd.adobe.com/spec/4fc78ad7-9d86-4677-5908-924f0a07144d-39f6/screen/b4517187-0256-40f7-8dbb-2b599f659346/Home/

**Comment by samakintunde37** [comment]
@konqa You working on this?

**Comment by konqa** [comment]
> @konqa You working on this?

Yes I just posted a PR for it.
